### ISSUE TITLE
works flawless in electron dev mode - does nothing in electron final build

### ISSUE THREAD

**Issue by valueerrorx** [LaunchMenu/node-global-key-listener#18]
i've tried a lot of things to make it work but i failed
(added node_modules/node-global-key-listener/bin to "asarUpack" section, added "node-global-key-listener" to vite.config.ts in "external" section.

it just doesn't seem to start at all - no error messages - nothing :-(

(using node 16.x, electron 16.x, vite. 2.7  on windows11)
the exact same thing happens on macos "big sur"

```npm run dev```` and it works...
after i build the electron executable it doesn't

in WinKeyServer.js it should spawn ../../bin/WinKeyServer.exe or fail silently afaiu 
so it seems it can't find the executable

how would i make sure it is included in the final build?

**Comment by sancarn** [comment]
Are you using the latest version? In https://github.com/LaunchMenu/node-global-key-listener/pull/15 I know one user appeared to get it working after `spawn` was changed to `execFile`.

**Comment by sancarn** [comment]
@TarVK mentioned to me a good point, though we have already changed this in the latest version, this version might not have been published to npm. I've now republished on version 0.0.14, so hopefully updating your npm package will work for you.

**Comment by vlsim** [comment]
Having the same exact issue here. Using Node 16, Electron 18 on Windows 10. Works perfectly in DEV mode, but does nothing when built. I have however not configured anything besides installing node-global-key-listener. I am on version 0.0.14.

**Comment by sancarn** [comment]
@vlsim Thanks for the investigation, I can't see any reason why that would occur, and I can't find issues in https://github.com/electron/asar/issues related to it, so not sure what would be happening...

**Comment by StenniHub** [comment]
I've got it working locally in both development and production with some modifications in a fork I made to allow adding the server executable path as part of the config.

If you have ngkl as a dependency and add it to externals under electronBuilder the executable should be accessable in production under the path `Path.join(__dirname, "node_modules/node-global-key-listener/bin/WinKeyServer.exe")`.

I instead opted to include ngkl as a developer dependency and manually include the WinKeyServer.exe in extraResources as it resulted in a slightly smaller production build.

**Comment by StenniHub** [comment]
It's not an ideal solution, other packages such as https://github.com/sindresorhus/trash does not require this workaround in production despite also executing binaries internally, but I have not figured out why that is.

**Comment by StenniHub** [comment]
The workaround has now been added in version 0.1.1. As an example of how to make it work in a packaged Electron app, feel free to copy the configuration from my save organizer project:
https://github.com/StenniHub/yaso/commit/db6dd170b786551e37797e5762146e2802485f96

Adding ngkl as an external should include it in the app asar and you can reference that path in production.
