### ISSUE TITLE
Capture mouse buttons

### ISSUE THREAD

**Issue by chlebon** [LaunchMenu/node-global-key-listener#21]
It would be great to implement capturing mouse buttons clicks just like iohook have.

**Comment by sancarn** [comment]
Very much doable for Windows, just detecting: WM_LBUTTONDBLCLK, WM_LBUTTONDOWN, WM_LBUTTONUP, WM_MBUTTONDBLCLK, WM_MBUTTONDOWN, WM_MBUTTONUP, WM_RBUTTONDBLCLK, WM_RBUTTONDOWN, WM_RBUTTONUP, WM_MOUSEHOVER, WM_MOUSEMOVE, WM_MOUSEWHEEL.

Not sure if you can detect these events on mac though.

Happy to accept a PR for this, if anyone wants to implement.
