### ISSUE TITLE
`IGlobalKeyListener` should allows `Promise<IGlobalKeyResult>`

### ISSUE THREAD

**Issue by IvanGodinez21** [LaunchMenu/node-global-key-listener#24]
### Issue description
In TypeScript, when I declare an async function which will be a `IGlobalKeyListener` data type that will be used for the `GlobalKeyboardListener().addListener` doesn't work because it doesn't allow to return a `Promise`

![image](https://user-images.githubusercontent.com/45635827/191599863-9089b31f-0fdf-4717-80ed-2948f2eafa1a.png)

![image](https://user-images.githubusercontent.com/45635827/191599930-d380263b-8519-4699-bd94-e23e63ae316e.png)

### Possible solution
Adding `Promise<IGlobalKeyResult>` (or even `Promise<void>`) to `(event: IGlobalKeyEvent, isDown: IGlobalKeyDownMap): IGlobalKeyResult;` seems to work.
Here is the example:

```ts
import { IGlobalKeyDownMap } from "./IGlobalKeyDownMap";
import { IGlobalKeyEvent } from "./IGlobalKeyEvent";
import { IGlobalKeyResult } from "./IGlobalKeyResult";
/**
 * The signature of a global key listener
 */
export declare type IGlobalKeyListener = {
    /**
     * Listens for key events
     * @param event The key event that was emitted
     * @param isDown The other keys that are registered to have been held while the event fired (Note this can become desynchronized if another program with higher priority captures and halts an event)
     * @returns Weather the event should be captured
     */
    (event: IGlobalKeyEvent, isDown: IGlobalKeyDownMap): IGlobalKeyResult | Promise<IGlobalKeyResult>; /* <----- Here */
};
//# sourceMappingURL=IGlobalKeyListener.d.ts.map
```
![image](https://user-images.githubusercontent.com/45635827/191602382-962fc1b1-a7ec-46fe-9dd8-f56e54ceb2a0.png)
No errors 🥳🎉

### Package version
v0.1.1

### TypeScript version
v4.8.3

### Node.js version
v16.16.0

**Comment by TarVK** [comment]
If I remember correctly, keeping things synchronous was a conscious decision. Generally I agree that having an interface allow for async callbacks is nicer in terms of flexibility. But in this case we're talking about the user's keyboard where delay really should be minimized. Any delay added in between firing the event and returning a result, is delay that the user will feel between them hitting a key on their keyboard and the character appearing. So I believe we decided to disallow asynchronicity here to discourage developers from adding a lot of delay here (potentially on accident). The computations for the callbacks should really be very minimal.

In case we would allow this, we would have to do more than change the interface. We would also have to introduce asynchronicity here: https://github.com/LaunchMenu/node-global-key-listener/blob/main/src/index.ts#L123

Realistically we would somehow want these callbacks to always have highest priority to be handled, similar to real hardware interrupts, but we don't know about such functionality in nodejs.

**Comment by IvanGodinez21** [comment]
I understand, I'll let this issue opened.
Also, I created a PR (#25), it only modifies the code as the example above in the description, if you want to close it go ahead

The PR includes:
- References this issue
- [x] Allow edits by maintainers

I would like to see this implementation, for my case, I need to use other modules that returns `Promises`.
I'll keep an eye on this module if you or any other collaborator change the code to allow asynchronous functions, for the moment I will find a way to fix this in my project.

Thanks for your reply @TarVK 💖
