### ISSUE TITLE
[Feature Request] Option to change directory for WinKeyServer/MacKeyServer

### ISSUE THREAD

**Issue by MrDiamondDog** [LaunchMenu/node-global-key-listener#33]
I noticed when I used the `pkg` module to package my node project into an exe, it would throw an error saying it could not find the WinKeyServer. I ended up having to change the path in `WinKeyServer.js` to get it to work. An option to change the path to the WinKeyServer would be nice to avoid this issue.

**Comment by sancarn** [comment]
I vaguely remember this to already be the case...? After #20

**Comment by MrDiamondDog** [comment]
It is. I did not know this existed. Thanks!

For anyone who needs the code:
```
new GlobalKeyboardListener({
    windows: {
        serverPath: "path/to/WinKeyServer.exe"
    }
});
```
