### ISSUE TITLE
Mouse is lagging when listening and moving while pressing a key

### ISSUE THREAD

**Issue by Krutsch** [LaunchMenu/node-global-key-listener#37]
The mouse lag so so big, so that it is not ideal to have it run in the background while gaming. It feels like the mouse is only moving 10% of the normal DPI.

System:
Win11
Node 21

**Comment by sancarn** [comment]
That really doesn't surprise me, unfortunately... 

We redirect **all mouse/keyboard events** across stdout, through nodejs, and back into the application. This will not be fixed until we can register shortcuts within the binary itself.

**Comment by sancarn** [comment]
See #6. Closing this as duplicate
